---
# - src: pf.common
# - src: pf.install
- src: geerlingguy.nodejs

# to have latest fix
#- src: gcoop-libre.systemd_resolved
- src: https://github.com/gcoop-libre/ansible_role_systemd_resolved
  version: master

